[package]
name = "crates_io_real_ip"
version = "0.0.0"
description = "Extract real client IP from X-Forwarded-For headers"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[dependencies]
http = "=1.3.1"
ipnetwork = "=0.21.1"
