[package]
name = "aws-ip-ranges"
version = "0.0.0"
description = "https://ip-ranges.amazonaws.com/ip-ranges.json as const structs"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[dependencies]
http = "=1.3.1"
ipnetwork = "=0.21.1"
